#!/usr/bin/env bash
umask 022

#--------------------------------------------------------------------
#--------------------------------------------------------------------
# Name: Cloud_StartPuppetWorkerNodes
# -----
# 
# Purpose: Script to enable the Puppet Agent on Worker Nodes in Swarm
# --------
#
# File History:
# -------------
# 17 Jul 19 - Initial Version ...................................donG
#--------------------------------------------------------------------
#--------------------------------------------------------------------

#set-x

Script=$(echo -e $0 | awk -F"/" '{print $NF}')
Server=$(uname -n)
LogFile=/Cloud/logs/${Script}.log
/syslib/rotate_logs ${LogFile}
exec &> >(tee -a "${LogFile}")

MANIFEST=${1}
MANIFEST=${MANIFEST:="NONE"}
COLLECTION=${2}
COLLECTION=${COLLECTION:="ALL"}
USER="svcdockr"
GOOD=()

if [ ${MANIFEST} != "NONE" ]
then
   for SERVER in $(grep -i itg /Cloud/dockerManifests/${MANIFEST} | awk -F: '{print $1}')
   do
      echo ${SERVER}
      echo -e "========================="
      ssh -o BatchMode=yes -l ${USER} -i /data/${USER}/.ssh/id_rsa -o StrictHostKeyChecking=no ${SERVER} "sudo systemctl start puppet" ; RC=${?}
      if [ ${RC} -eq 0 ]
      then
         echo -e "Puppet service was successfully started on ${SERVER}"
         GOOD+="${SERVER}\n"
      else
         echo -e "Puppet service was NOT successfully started on ${SERVER}... INVESTIGATE!!!"
      fi
      echo -e "========================="
   done
else
   echo -e "YOU DID NOT PROVIDE A VALID MANIFEST FILE!!!!!"
   exit 99
fi

MailList=$(cat /Cloud/scripts/MailList.txt)
MESSAGE="\nThe following nodes were successfully drained, rebooted, and set back to active with no issue.\n"
MESSAGE+="${GOOD}"

if [ ${GOOD} ]
then
    echo -e "${MESSAGE}"
    echo -e "${MESSAGE}" | mailx -s "The puppet agent was started on ${COLLECTION} worker nodes for the ${MANIFEST} manifest" ${MailList}
fi

exit
